### ISSUE TITLE
Migration error during upgrade cluster from 6 to 7

### ISSUE THREAD

**Issue by marcoscarrilho** [ossobv/proxmove#36]
Hi, 

VM migrations is working from Proxmox Cluster 5 to 6. After upgrade Cluster 6 to 7, proxmove is failing
Now i try migrate from Cluster 5 to Cluster 7 and get this error:

```
2021-10-07 10:41:22,292: DEBUG: Checking storage prerequisites
2021-10-07 10:41:22,292: DEBUG: (exec) ssh -c aes128-gcm@openssh.com,aes128-cbc root@rs17.unifesp.br which ssh rsync
2021-10-07 10:41:22,478: DEBUG: (exec) ssh -c aes128-gcm@openssh.com,aes128-cbc root@rs17.unifesp.br test -d /mnt/pve/vol_vm_proxmox/tmp
2021-10-07 10:41:22,662: DEBUG: (exec) ssh -c aes128-gcm@openssh.com,aes128-cbc root@rs08.epm.br which ssh rsync
2021-10-07 10:41:22,815: DEBUG: (exec) ssh -c aes128-gcm@openssh.com,aes128-cbc root@rs08.epm.br test -d /mnt/pve/vol_dti_rack/tmp
2021-10-07 10:41:22,966: INFO: Attempt moving DTI-rack<aee6f0ec> => dc-prod<63d82f4e> (node 'ts01'): dckr
2021-10-07 10:41:22,966: INFO: - source VM dckr@rs05<qemu/150/stopped>
2021-10-07 10:41:22,967: INFO: - storage 'ide2': None,media=cdrom (host=<unknown>, guest=<unknown>)
2021-10-07 10:41:22,967: INFO: - storage 'scsi0': vol_dti_rack:150/vm-150-disk-0.qcow2,size=200G (host=200.0GiB, guest=200.0GiB)
2021-10-07 10:41:22,967: DEBUG: - setting boot=cd workaround for 6.1+6.3 mixcluster
Traceback (most recent call last):
  File "./proxmove", line 1976, in _start_moving_vm
    dst_vm = self.dst_pve.get_vm(
  File "./proxmove", line 565, in get_vm
    raise ProxmoxVm.DoesNotExist(
__main__.DoesNotExist: VM named 'dckr' not found in cluster 'dc-prod'; do you have the PVEVMAdmin role?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./proxmove", line 2292, in <module>
    main()
  File "./proxmove", line 2288, in main
    vmmover.run(options.dry_run)
  File "./proxmove", line 1928, in run
    self.move_vm(vm, translator, dry_run)
  File "./proxmove", line 1968, in move_vm
    dst_vm = self._start_moving_vm(src_vm, translator)
  File "./proxmove", line 1984, in _start_moving_vm
    poolid=src_vm.poolid)
  File "./proxmove", line 1354, in poolid
    return self.cluster.pools.get_poolid(self.id)
  File "./proxmove", line 281, in get_poolid
    self._populate_cache()
  File "./proxmove", line 323, in _populate_cache
    vmid = int(memberdict['vmid'])
KeyError: 'vmid'
```

I changed the user to root@pam and I still have the same problem.

Anyone can help me?

Thanks.

**Comment by wdoekes** [comment]
```patch
diff --git a/proxmove b/proxmove
index f75b8ff..2f9aaba 100755
--- a/proxmove
+++ b/proxmove
@@ -320,9 +320,13 @@ class ProxmoxPools(object):
                 raise
 
             for memberdict in poolinfo['members']:
-                vmid = int(memberdict['vmid'])
-                assert vmid not in ret, (ret, memberdict)
-                ret[vmid] = poolid
+                # For {'type': 'qemu'}, we'll get a 'vmid', but
+                # other things can be put in a pool too, like
+                # {'type': 'storage'}.
+                if 'vmid' in memberdict:
+                    vmid = int(memberdict['vmid'])
+                    assert vmid not in ret, (ret, memberdict)
+                    ret[vmid] = poolid
 
         self._vm_to_pool = ret
 
```
This should fix things for you.

**Comment by marcoscarrilho** [comment]
> ```diff
> diff --git a/proxmove b/proxmove
> index f75b8ff..2f9aaba 100755
> --- a/proxmove
> +++ b/proxmove
> @@ -320,9 +320,13 @@ class ProxmoxPools(object):
>                  raise
>  
>              for memberdict in poolinfo['members']:
> -                vmid = int(memberdict['vmid'])
> -                assert vmid not in ret, (ret, memberdict)
> -                ret[vmid] = poolid
> +                # For {'type': 'qemu'}, we'll get a 'vmid', but
> +                # other things can be put in a pool too, like
> +                # {'type': 'storage'}.
> +                if 'vmid' in memberdict:
> +                    vmid = int(memberdict['vmid'])
> +                    assert vmid not in ret, (ret, memberdict)
> +                    ret[vmid] = poolid
>  
>          self._vm_to_pool = ret
>  
> ```
> 
> This should fix things for you.

It worked!

Now I get your point, after all it has nothing to do with migrating to version 7, right? The problem happens when there is storage in a pool.

Thanks again @wdoekes
