### ISSUE TITLE
Cannot migrate VM between clusters when disk format=raw

### ISSUE THREAD

**Issue by stijnsoethout** [ossobv/proxmove#49]
Proxmove fails to move VM when disk (virtio) format type = raw
```
2023-11-07 21:13:14,982: INFO: Begin copy of 'virtio0' (<disk>:vm-129-disk-0,format=raw,iops_rd=500,iops_wr=500,mbps_rd=100,mbps_wr=100,size=20G) to local-zfs (vm-111-disk-0)
Traceback (most recent call last):
  File "proxmove", line 2420, in <module>
    main()
  File "proxmove", line 2416, in main
    vmmover.run(options.dry_run)
  File "proxmove", line 2038, in run
    self.move_vm(vm, translator, dry_run)
  File "proxmove", line 2081, in move_vm
    dst_vm = self._start_moving_vm(src_vm, translator)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "proxmove", line 2106, in _start_moving_vm
    self._move_vm_volumes(src_vm, dst_vm, move_mode=self.MOVE_INITIAL)
  File "proxmove", line 2165, in _move_vm_volumes
    self._move_vm_volume(src_vm, dst_vm, volume_key, volume, move_mode)
  File "proxmove", line 2179, in _move_vm_volume
    dst_vm.create_volume(
  File "proxmove", line 1489, in create_volume
    new_volume = source_volume.clone(
                 ^^^^^^^^^^^^^^^^^^^^
  File "proxmove", line 1724, in clone
    new_path, new_format = self.storage.copy(
                           ^^^^^^^^^^^^^^^^^^
  File "proxmove", line 704, in copy
    assert not src_format, src_format
AssertionError: raw
```

**Comment by wdoekes** [comment]
Turned out to be superfluous format=raw properties. Fixed with 6ba60cc. Thanks!
