### ISSUE TITLE
Add support for moving LXC containers

### ISSUE THREAD

**Issue by aaboonstra** [ossobv/proxmove#5]
When trying to move an LXC container from clusterA to clusterB the procedure fails:

`alex@alex-desktop:~$ proxmove pve-clusterA pve-clusterB nodeA storagepoolA containerA
Traceback (most recent call last):
  File "/usr/local/bin/proxmove", line 1495, in <module>
    main()
  File "/usr/local/bin/proxmove", line 1485, in main
    vmmover.prepare()
  File "/usr/local/bin/proxmove", line 1148, in prepare
    self.prepare_vm_list()
  File "/usr/local/bin/proxmove", line 1160, in prepare_vm_list
    vm = self.src_pve.get_vm(vm_name)
  File "/usr/local/bin/proxmove", line 387, in get_vm
    res[0], api=self.api, cluster=self)
  File "/usr/local/bin/proxmove", line 843, in from_dict
    vm.get_config()  # get config and check for pending changes at once
  File "/usr/local/bin/proxmove", line 889, in get_config
    self.name = next_config['name']
KeyError: 'name'`

**Comment by wdoekes** [comment]
After a few fixes, this breaks on missing ostemplate:
https://forum.proxmox.com/threads/create-lxc-container-via-curl-api-bad-request-400.27321/

We need to set/add an ostemplate, even when we'll overwrite it later on.

```
ERROR POST https://DSTHOST:443/api2/json/nodes/mc11-6/lxc {
'net1': 'bridge=vmbr,hwaddr=...:38:35,ip=10....10/24,name=eth1,type=veth',
'hostname': 'NEWHOST--CREATING', 'rootfs': 'pool0-pve2-ssd:subvol-105-disk-1,size=20G',
'searchdomain': '...11', 'cpuunits': 1024, 'memory': 2048, 'cpulimit': '2', 'swap': 0,
'net0': 'bridge=vmbr0,gw=....1,hwaddr=....64:34,ip=.....75/24,name=eth0,type=veth',
'nameserver': '....11 8.8.8.8', 'ostype': 'ubuntu', 'vmid': 160, 'arch': 'amd64'}
None '{"data":null,"errors":{"ostemplate":"property is missing and it is not optional"}}'
```
Temp fixes:
```
--- a/proxmove
+++ b/proxmove
@@ -96,6 +96,20 @@ class _HumanSizeScan(object):
 human_size_scan = _HumanSizeScan()
 
 
+def get_config_name(type_, config):
+    """
+    For 'lxc', the unique name is in 'hostname'. For others it is in 'name'.
+    """
+    print(config)
+
+    if type_ == 'lxc':
+        assert 'name' not in config, config
+        return config['hostname']
+
+    assert 'hostname' not in config, config
+    return config['name']
+
+
 class ProxmoveError(Exception):
     pass
 
@@ -298,14 +312,15 @@ class ProxmoxCluster(object):
         if not nodeid:
             nodeid = self.get_random_node()
 
+        print(config)
         log.info('Creating new VM {!r} on {!r}, node {!r}'.format(
-            config['name'], self.name, nodeid))
+            get_config_name(type_, config), self.name, nodeid))
 
         # Create disks according to config. Temporarily set ide\d+ and
         # virtio\d+ devices to none until we can get them copied over.
         mutable_config = {}
         for key, value in config.items():
-            if key == 'name':
+            if key in ('name', 'hostname'):
                 mutable_config[key] = value + SUFFIX_CREATING
             elif re.match(
                     '^({})\d+$'.format('|'.join(PROXMOX_VOLUME_TYPES)), key):
@@ -322,11 +337,11 @@ class ProxmoxCluster(object):
         # Wait a while to ensure that we get the VM.
         log.info(
             '- created new VM {!r} as {}; waiting for it to show up'.format(
-                mutable_config['name'], vmhash))
+                get_config_name(type_, mutable_config), vmhash))
         for i in range(30):
             try:
                 self._cache = {}  # purge cache, we expect changes
-                vm = self.get_vm(mutable_config['name'])
+                vm = self.get_vm(get_config_name(type_, mutable_config))
             except ProxmoxVm.DoesNotExist:
                 pass
             else:
@@ -334,7 +349,7 @@ class ProxmoxCluster(object):
             time.sleep(1)
         else:
             raise ProxmoveError('Could not get newly created VM {!r}'.format(
-                mutable_config['name']))
+                get_config_name(type_, mutable_config)))
 
         log.info('- created new VM {!r}: {}'.format(vm.name, vm))
         return vm
@@ -823,7 +838,8 @@ class ProxmoxStorageZfs(ProxmoxStorage):
     def set_path(self, value):
         assert value.startswith('zfs:'), value
         pool_name = value[4:]
-        valid_characters = string.ascii_letters + string.digits + '_-'
+        # FIXME: check that entire path exists?
+        valid_characters = string.ascii_letters + string.digits + '_-/'
         if not all(i in valid_characters for i in pool_name):
             raise PrepareError(
                 'invalid characters in zfs pool name found {!r} storage '
@@ -858,11 +874,15 @@ class ProxmoxVm(object):
         """
         Check whether we can move this VM.
         """
+        if self.type == 'lxc':
+            # No pending changes
+            return
+
         config = self.get_config()
 
         # Check pending. We expect a list of dictionaries with a 'key'
         # key and 'value' and/or 'pending' keys.
-        pending_config = self.api_vm.pending.get()  # may not exist for lxc
+        pending_config = self.api_vm.pending.get()  # does not exist for lxc
         pending = []
         for dict_ in pending_config:
             keys = dict_.keys()
@@ -886,7 +906,7 @@ class ProxmoxVm(object):
         """
         if 'config' not in self._cache:
             next_config = self.api_vm.config.get()
-            self.name = next_config['name']
+            self.name = get_config_name(self.type, next_config)
             self._cache['config'] = next_config
         return self._cache['config']
 
@@ -1301,7 +1321,7 @@ class VmMover(object):
                 dst_vm.create_volume(key, volume, storage=storage)
 
             # Done? Rename both.
-            dst_vm.rename(dst_config['name'])
+            dst_vm.rename(dst_vm.get_config_name(dst_config))
             src_vm.rename(src_vm_name + SUFFIX_MIGRATED)
             src_vm.add_comment('{} UTC: Migrated to {}'.format(
                 datetime.utcnow(), dst_vm))
```

**Comment by wdoekes** [comment]
Nobody has LXC in PVE, right?

**Comment by lifeboy** [comment]
What does "nobody has LXC in PVE, right?" mean?  It is <sarc>?  Whenever possible we prefer to use LXC over KVM, simply because it's so much more efficient.

The original comment is from 2017, which is 4 years ago, so has anything changed?

**Comment by wdoekes** [comment]
There are certainly valid use cases for LXC. But it does not fit in our PVE/VM workflow nor security model.

Perhaps I should've written "nobody at OSSO".

**Comment by lifeboy** [comment]
Ah, yes, that makes more sense :-)
