### ISSUE TITLE
400 Bad Request: Parameter verification failed.

### ISSUE THREAD

**Issue by N0TScrooge** [ossobv/proxmove#52]
./proxmove --no-verify-ssl --debug aaaaptvzb17a bbbbun763bu bbbbun763bu nvme1n1p1_960gb  wastebin

│ groupid       │ comment │ users          │
 │ moveusergroup │         │ uservmmove@pve │

group moveusergroup  role granted PVEVMAdmin, PVESDNAdmin, PVEPoolAdmin, PVEAuditor and PVEAdmin

and 

user uservmmove@pve  role granted PVEVMAdmin, PVESDNAdmin, PVEPoolAdmin, PVEAuditor and PVEAdmin

```
2024-08-02 10:59:26,337: INFO: Attempt moving aaaaptvzb17a<9355359cd7afbae4> => bbbbun763bu<faa83925c9641325> (node 'bbbbun763bu'): wastebin
2024-08-02 10:59:26,337: INFO: - source VM wastebin@aaaaptvzb17a<lxc/100/running>
2024-08-02 10:59:26,338: DEBUG: - setting boot=cd workaround for 6.1+6.3 mixcluster
2024-08-02 10:59:26,342: INFO: Creating new VM 'wastebin--CREATING' on 'bbbbun763bu', node 'bbbbun763bu'
2024-08-02 10:59:26,346: DEBUG: - creating VM: {'memory': 2048, 'features': 'keyctl=1,nesting=1', 'unprivileged': 1, 'tags': 'proxmox-helper-scripts', 'net0': 'virtio=BC:24:11:93:8B:9B,bridge=vmbr0', 'name': 'wastebin--CREATING', 'onboot': 1, 'cores': 4, 'boot': 'cd', 'vmid': 100}
2024-08-02 10:59:26,361: ERROR: Failed to create VM with parameters:

  # https://bbbbun763bu.domain.name:8006/api2/json
  api.nodes("bbbbun763bu/qemu").create(**{'memory': 2048, 'features': 'keyctl=1,nesting=1', 'unprivileged': 1, 'tags': 'proxmox-helper-scripts', 'net0': 'virtio=BC:24:11:93:8B:9B,bridge=vmbr0', 'name': 'wastebin--CREATING', 'onboot': 1, 'cores': 4, 'boot': 'cd', 'vmid': 100})

Do you have PVEVMAdmin + PVESDNAdmin perms?

Traceback (most recent call last):
  File "/root/proxmove/proxmove", line 477, in create_vm
    vmhash = getattr(api_node, 'qemu').create(**mutable_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proxmoxer/core.py", line 135, in create
    return self.post(*args, **data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proxmoxer/core.py", line 126, in post
    return self(args)._request("POST", data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proxmoxer/core.py", line 105, in _request
    raise ResourceException(
proxmoxer.core.ResourceException: 400 Bad Request: Parameter verification failed.
Traceback (most recent call last):
  File "/root/proxmove/proxmove", line 2457, in <module>
    main()
  File "/root/proxmove/proxmove", line 2453, in main
    vmmover.run(options.dry_run)
  File "/root/proxmove/proxmove", line 2075, in run
    self.move_vm(vm, translator, dry_run)
  File "/root/proxmove/proxmove", line 2118, in move_vm
    dst_vm = self._start_moving_vm(src_vm, translator)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/proxmove/proxmove", line 2136, in _start_moving_vm
    dst_vm = self.dst_pve.create_vm(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/proxmove/proxmove", line 477, in create_vm
    vmhash = getattr(api_node, 'qemu').create(**mutable_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proxmoxer/core.py", line 135, in create
    return self.post(*args, **data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proxmoxer/core.py", line 126, in post
    return self(args)._request("POST", data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/proxmoxer/core.py", line 105, in _request
    raise ResourceException(
proxmoxer.core.ResourceException: 400 Bad Request: Parameter verification failed.
```
### .proxmoverc 

[pve:aaaaptvzb17a]
api=https://uservmmove@pve:yyyyy@aaaaptvzb17a.domain.name:8006

  [storage:aaaaptvzb17a:zfsraid2main] ; local disk on node1 only
  ssh=root@aaaaptvzb17a.domain.name:22
  path=/zfsraid2main/
  temp=/tmp

[pve:bbbbun763bu]
api=https://uservmmove@pve:zzzzz@bbbbun763bu.domain.name:8006

  [storage:bbbbun763bu:nvme1n1p1_960gb@bbbbun763bu]
  ssh=root@bbbbun763bu.domain.name:22
  path=zfs:nvme1n1p1_960gb/
  temp=/tmp

**what am I doing wrong**

**Comment by N0TScrooge** [comment]
after installed proxmoxer-2.0.1

```
2024-08-02 11:44:59,321: DEBUG: Parsing config file: ~/.proxmoverc
2024-08-02 11:44:59,322: DEBUG: (api) Connecting to aaaaptvzb17a.domain.name
/root/proxmove/env/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'aaaaptvzb17a.domain.name'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/root/proxmove/env/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'aaaaptvzb17a.domain.name'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-08-02 11:44:59,510: DEBUG: (api) Connecting to bbbbun763bu.domain.name
/root/proxmove/env/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'bbbbun763bu.domain.name'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/root/proxmove/env/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'bbbbun763bu.domain.name'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/root/proxmove/env/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'bbbbun763bu.domain.name'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-08-02 11:44:59,652: DEBUG: (api) 'bbbbun763bu' nodes: [{'status': 'online', 'mem': 2455199744, 'type': 'node', 'level': '', 'uptime': 40929, 'maxmem': 134921940992, 'cpu': 0.000672902227306372, 'disk': 3940122624, 'maxdisk': 17254105088, 'maxcpu': 72, 'ssl_fingerprint': 'E4:74:9E:AC:99:3C:F1:AA:A9:A1:FD:5C:B4:72:6D:E0:BC:8C:A5:7C:E5:D3:52:3F:0C:22:D9:55:ED:5C:01:41', 'id': 'node/bbbbun763bu', 'node': 'bbbbun763bu'}]
2024-08-02 11:44:59,652: DEBUG: Sanity checks and preparation
2024-08-02 11:44:59,652: DEBUG: Checking VMs existence on source and destination
/root/proxmove/env/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'aaaaptvzb17a.domain.name'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/root/proxmove/env/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'bbbbun763bu.domain.name'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/root/proxmove/env/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'aaaaptvzb17a.domain.name'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-08-02 11:44:59,663: DEBUG: Checking for problematic config in 1 VMs to move
2024-08-02 11:44:59,663: DEBUG: Found 1 relevant storages: nvme1n1p1_960gb
2024-08-02 11:44:59,663: DEBUG: Checking storage prerequisites
2024-08-02 11:44:59,663: DEBUG: (exec) ssh -p 22 root@bbbbun763bu.domain.name /bin/true
2024-08-02 11:45:00,032: DEBUG: (exec) ssh -p 22 root@bbbbun763bu.domain.name which ssh zfs mbuffer rsync
2024-08-02 11:45:00,381: DEBUG: (exec) ssh -p 22 root@bbbbun763bu.domain.name mkdir -p /tmp
2024-08-02 11:45:00,733: INFO: Attempt moving aaaaptvzb17a<9355359cd7afbae4> => bbbbun763bu<faa83925c9641325> (node 'bbbbun763bu'): wastebin
2024-08-02 11:45:00,733: INFO: - source VM wastebin@aaaaptvzb17a<lxc/100/running>
2024-08-02 11:45:00,733: DEBUG: - setting boot=cd workaround for 6.1+6.3 mixcluster
/root/proxmove/env/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'aaaaptvzb17a.domain.name'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-08-02 11:45:00,737: INFO: Creating new VM 'wastebin--CREATING' on 'bbbbun763bu', node 'bbbbun763bu'
/root/proxmove/env/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'bbbbun763bu.domain.name'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-08-02 11:45:00,741: DEBUG: - creating VM: {'onboot': 1, 'cores': 4, 'features': 'keyctl=1,nesting=1', 'unprivileged': 1, 'net0': 'virtio=BC:24:11:93:8B:9B,bridge=vmbr0', 'tags': 'proxmox-helper-scripts', 'name': 'wastebin--CREATING', 'memory': 2048, 'boot': 'cd', 'vmid': 100}
/root/proxmove/env/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'bbbbun763bu.domain.name'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-08-02 11:45:00,754: ERROR: Failed to create VM with parameters:

  # https://bbbbun763bu.domain.name:8006/api2/json
  api.nodes("bbbbun763bu/qemu").create(**{'onboot': 1, 'cores': 4, 'features': 'keyctl=1,nesting=1', 'unprivileged': 1, 'net0': 'virtio=BC:24:11:93:8B:9B,bridge=vmbr0', 'tags': 'proxmox-helper-scripts', 'name': 'wastebin--CREATING', 'memory': 2048, 'boot': 'cd', 'vmid': 100})

Do you have PVEVMAdmin + PVESDNAdmin perms?

Traceback (most recent call last):
  File "/root/proxmove/env/./proxmove", line 477, in create_vm
    vmhash = getattr(api_node, 'qemu').create(**mutable_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/proxmove/env/lib/python3.11/site-packages/proxmoxer/core.py", line 181, in create
    return self.post(*args, **data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/proxmove/env/lib/python3.11/site-packages/proxmoxer/core.py", line 172, in post
    return self(args)._request("POST", data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/proxmove/env/lib/python3.11/site-packages/proxmoxer/core.py", line 149, in _request
    raise ResourceException(
proxmoxer.core.ResourceException: 400 Bad Request: Parameter verification failed. - {'unprivileged': 'property is not defined in schema and the schema does not allow additional properties', 'features': 'property is not defined in schema and the schema does not allow additional properties'}
Traceback (most recent call last):
  File "/root/proxmove/env/./proxmove", line 2457, in <module>
    main()
  File "/root/proxmove/env/./proxmove", line 2453, in main
    vmmover.run(options.dry_run)
  File "/root/proxmove/env/./proxmove", line 2075, in run
    self.move_vm(vm, translator, dry_run)
  File "/root/proxmove/env/./proxmove", line 2118, in move_vm
    dst_vm = self._start_moving_vm(src_vm, translator)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/proxmove/env/./proxmove", line 2136, in _start_moving_vm
    dst_vm = self.dst_pve.create_vm(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/proxmove/env/./proxmove", line 477, in create_vm
    vmhash = getattr(api_node, 'qemu').create(**mutable_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/proxmove/env/lib/python3.11/site-packages/proxmoxer/core.py", line 181, in create
    return self.post(*args, **data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/proxmove/env/lib/python3.11/site-packages/proxmoxer/core.py", line 172, in post
    return self(args)._request("POST", data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/proxmove/env/lib/python3.11/site-packages/proxmoxer/core.py", line 149, in _request
    raise ResourceException(
proxmoxer.core.ResourceException: 400 Bad Request: Parameter verification failed. - {'unprivileged': 'property is not defined in schema and the schema does not allow additional properties', 'features': 'property is not defined in schema and the schema does not allow additional properties'}

```
